export const REQUEST_START_GAME = 'REQUEST_START_GAME';
export const CALLBACK_GAME_ROLE = 'CALLBACK_GAME_ROLE';
export const CALLBACK_PLAYERS_COUNT = 'CALLBACK_PLAYERS_COUNT';
export const CALLBACK_GAME_TIMER = 'CALLBACK_GAME_TIMER';
export const CALLBACK_LOCATIONS_LIST = 'CALLBACK_LOCATIONS_LIST';
export const SET_KEY = 'SET_KEY';
